export const GET_PRODUCT_SEARCH = 'GET_PRODUCT_SEARCH';
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const POST_NEW_PRODUCT = 'POST_NEW_PRODUCT';
export const POST_NEW_STRAIN = 'POST_NEW_PRODUCT';
export const POST_NEW_CATEGORY = 'POST_NEW_PRODUCT';
export const GET_STRAIN_LIST = 'GET_STRAIN_LIST';
